---
# tasks file for swarmmanager

- name: "Init swarm"
  docker_swarm:
    state: present

- name: "Get swarm information"
  docker_swarm_info:
  register: info

- name: "Deploy the app"
  docker_stack:
    state: present
    name: sweet-factory
    compose:
      - /home/radio/docker-compose.yaml 