version: "3.8"
services:
  sweet-factory:
    container_name: sweet-factory
    image: radiofam24/sweet-factory-front:latest
    build: ./sweet-factory
    deploy:
      replicas: 1
    networks:
      - sweet-net
  cake-api:
    container_name: cake-api
    image: radiofam24/sweet-factory-cake:latest
    build: ./cake-api
    deploy:
      replicas: 1
    networks:
      - sweet-net
  milkshake-api:
    container_name: milkshake-api
    image: radiofam24/sweet-factory-shake:latest
    build: ./milkshake-api  
    deploy:
      replicas: 1
    networks:
      - sweet-net
  toothache-api:
    container_name: toothache-api
    image: radiofam24/sweet-factory-tooth:latest
    build: ./toothache-api
    deploy:
      replicas: 1
    networks:
      - sweet-net
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - sweet-net
    depends_on:
      - "sweet-factory"
networks:
  sweet-net:

  