---
# tasks file for dockerinstall

- name: "Install dependencies"
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3
    - pythone-pip

- name: "Add gpg key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: "Add repo"
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: "Install docker engine"
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: "Add jenkins to the docker group"
  user:
    name: jenkins
    groups: docker
    append: yes

- name: "Install using pip"
  pip:
    name:
      - docker
      - jsondiff
    executable: pip3
